global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "chia-exporter"
    static_configs:
      - targets: ["chia-exporter:9914"]
        labels:
          application: 'chia-blockchain'
          network: 'mainnet'
