name: Build Docker Images

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

jobs:
  package:
    uses: Chia-Network/actions/.github/workflows/docker-build.yaml@main
    with:
      push: ${{ github.event_name != 'pull_request' }}
