name: Test/Lint/Fmt/Vet
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make test
